services:
  alastor-radio-daemon:
    image: ghcr.io/bnfone/discord-bot-alastor
    container_name: alastor
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=your-bot-token
      - CONFIG_PATH=/app/config.yaml
      - BOT_PREFIX=!
    volumes:
      - ./config.yaml:/app/config.yaml:ro